<a href="https://colab.research.google.com/github/Mohammad-Shiblu/Pytorch_Tutorial/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch Fundamentals


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introductions to tensors

### Creating tensors

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int

scalar.item()

7

In [5]:
#Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9, 5],
                        [2, 4, 5, 7]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 5],
         [2, 4, 5, 7]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 4])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR[0]

tensor([[1, 2, 3, 4],
        [3, 6, 9, 5],
        [2, 4, 5, 7]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many networks learn is that they start with tensors full of random numbers and then adjust those ranodm numbers to better represent the dats.

`start with randome numbers -> look at the data -> update random numbers -> look at the data -> update random numbers`

In [16]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5609, 0.6930, 0.5972, 0.3908],
        [0.7992, 0.7228, 0.4932, 0.3402],
        [0.8017, 0.1900, 0.1634, 0.3059]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, width and the color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
# zeros and ones tensor
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
# Create a tensor of ones

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range() deprecated
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [23]:
# Creating tensor of same size zeros tensor of another tensor
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# float_32_tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what data type is a tensor
                               device = None, # what device is your tensor on (cpu and cuda)
                               requires_grad= False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
## Getiing information from tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2764, 0.5317, 0.7730, 0.7106],
        [0.8803, 0.2163, 0.1372, 0.8872],
        [0.8197, 0.9958, 0.3572, 0.4133]])

In [28]:
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2764, 0.5317, 0.7730, 0.7106],
        [0.8803, 0.2163, 0.1372, 0.8872],
        [0.8197, 0.9958, 0.3572, 0.4133]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors

Tensors operation include :
 Addition, Subtraction, Multiplication, division, Matrix multiplication

In [29]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [31]:
# try out pytorch in built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
# Matrix Multiplication (torch.mm also does matrix multiplication)
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.1669, 0.0671, 0.4557],
        [0.1806, 0.1645, 0.8852],
        [0.3163, 0.1943, 1.1497]])

## Finding the mean, max , min, sum etc (tensor aggregation)

In [35]:
# create a tensor
x = torch.arange(1, 100, 10)
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [36]:
# Find the min (both torch.min and x.min() works)
torch.min(x), x.min()

(tensor(1), tensor(1))

In [37]:
# Find the mean (torch mean does not work with long integer need float data type)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [38]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [39]:
## Find the positional min and max
x.argmin()


tensor(0)

In [40]:
x[0]

tensor(1)

In [41]:
x.argmax()

tensor(9)

In [42]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensor

* Reshaping - Reshape a input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memeory as the original tensor
*stacking - combine multiole tensors on top of each other (vstack) or side by side, hstack
* squeeze - remove all `1` dimensions from a tensors
* unsqueeze - Add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [43]:
# Lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
# Add an extra dimentions
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
# change the biew, similar to reshape. but share the same memory (change in z will also lead to change in x)

z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [47]:
# stack tensors on top of each other (dim =0 stack along the rows increase the rows numbers)
# dim =1 stack along the column, increase the number of column
x_stacked = torch.stack([x, x, x, x], dim =1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [48]:
# torch squeeze()- remove all single dimensions from target tensor
x_reshaped


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [49]:
x_reshaped.shape

torch.Size([1, 9])

In [50]:
# squeeze remove the all dim of size 1 (like above (1,9) tensors become 9 dim)
x_reshaped.squeeze()


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
# removed the single dim
x_reshaped.squeeze().shape

torch.Size([9])

In [52]:
# unsqueeze add a single dim to a target tensor at a specific dim
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
x_unsqueezed

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [53]:
x_unsqueezed.shape

torch.Size([1, 1, 9])

In [54]:
# Permute
x_original = torch.rand(size=(224, 224, 3))

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # they share the same location
x_permuted.shape

torch.Size([3, 224, 224])

In [55]:
# same as view they share the same memory
x_original[0, 0, 0] = 1111
x_permuted[0, 0, 0], x_original[0, 0, 0]

(tensor(1111.), tensor(1111.))

##  Indexing
Indexing with pytorch is very similar to numpy

In [56]:
# Create a tensor
import torch
x= torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x[0, 0]

tensor([1, 2, 3])

In [59]:
x[:, 1]

tensor([[4, 5, 6]])

In [60]:
# Get all values of 0th and 1st dimention but only index 1 of 2nd dime
x[:, :, 1]

tensor([[2, 5, 8]])

## Pytorch tensors & Numpy
Numpy is a popular scientific Python numerical library

And because of this, Pytorch has functionality to interact with it.

* Data in numpy, want in Pytorch tensor -> `torch.from _numpy(ndarray)`

* Pytorch tensor -> Numpy -> `torch.tensor.numpy()`



In [61]:
# Numpy array tot tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

numpy default datatype float64, pytorch default datatype float32

In [62]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural networks learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> agian -> again -> again...`

To reduce the randomness in neural networks and pytorch comes of a **random seeds**.
Essentially what the random seed does is "flavour" the randomness.

In [63]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)


tensor([[0.1139, 0.0752, 0.7362, 0.1293],
        [0.1030, 0.2523, 0.5902, 0.8123],
        [0.3026, 0.2521, 0.2382, 0.6480]])
tensor([[0.8433, 0.6223, 0.9279, 0.5022],
        [0.1462, 0.2858, 0.9880, 0.5732],
        [0.5009, 0.8940, 0.5336, 0.9819]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# Lets make some random but reproducible tensors

In [64]:
import torch

# set the random seed
Random_seed = 42
torch.manual_seed(Random_seed)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(Random_seed)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)

connect pytorch to your own GPU

In [65]:
# check for GPU
import torch
torch.cuda.is_available()


False

In [66]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [67]:
# count the number of devices (search pytorch device agnostic code)
# running different model in different gpu
torch.cuda.device_count()

0

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in the faster computation.


In [68]:
# create a tensor
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [69]:
tensor_on_gpu = tensor.to(device) # this to function noved to tensor to the current active device
tensor_on_gpu

tensor([1, 2, 3])

In [70]:
### Moving tensor to CPU
# If tensor in on GPU, can't transform it to Numpy (Numpy can't work in GPU)
tensor_on_gpu.numpy()




array([1, 2, 3])

In [71]:
# To fix the GPU tensor with NUmpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [72]:
tensor_on_gpu

tensor([1, 2, 3])